name: Build&Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install node modules
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Start backend
      run: npm run server &

    - name: Execute static security tests
      run: npm audit
    
    - name: Execute integration tests
      run: npm test
